= Wisdom of the crowd
:linkattrs:
:stem:
:published_at: 2017-05-11

This week, GSoC started with the "community bonding" phase. I already feel pretty bonded with my software community (in fact I constitute stem:[1/3] of it), so I use the time to reach out to the larger neuroimaging community regarding one of the first issues I want to address:

*What is the best way to distribute the Python version of CBS Tools?*

I have previously discussed this question with my mentors and other colleagues, and one suggestion that came up is to deploy the tools via https://www.docker.com/[Docker]. In order to find out what neuroimaging folks think about docker I have started discussion threads on https://neurostars.org/t/using-docker-to-distribute-highres-neuroimaging-software/442[neurostars] and in the https://brainhack-slack-invite.herokuapp.com/[brainhack slack team].

I know very little about docker myself, so I also started watching some https://www.youtube.com/playlist?list=PLoYCgNOIyGAAzevEST2qm2Xbe3aeLFvLc[tutorials]. Whether we end up using it or not, my feeling is it won't hurt in the future to know a thing or two about docker.
