= Travis CI
:linkattrs:
:published_at: 2017-08-18

This week I set up continuous integration (CI) with https://travis-ci.org/[travis] for our project. I knew very little about travis -- or CI -- before, and had thought of it more in terms of running automatic tests. And we don't even have unit tests yet.

But it turns out travis also very useful for another reason: to automatically build the package -- including compiling of Java classes, wrappers and all -- and deploy it to PyPI. With the build script from <<2017-07-16-Brainhack-Vancouver.adoc#,Brainhack Vancouver>> and as usual lots of peeking into other packages, it was easier than I had thought to put together the https://github.com/nighres/nighres/blob/master/.travis.yml[travis.yml] script. 

We currently deploy to TestPyPI everytime changes are pushed to master. But once Nighres is ready for the official release, it's easy to switch to the real PyPI servers and deploy only tagged releases.

And when we have proper tests for the Python code, we can extend the travis script to run them against different versions of Python and the dependencies (Numpy and Nibabel), to ensure that changes to the existing code don't break current functionality.

And at the end of the second last week of GSoC coding, what could be more satisfying than:

[#build-passing]
image:https://travis-ci.org/nighres/nighres.svg?branch=master["Build Status", link="https://travis-ci.org/nighres/nighres"]
